apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      enableServiceLinks: false
      containers:
      - name: pgbouncer
        image: bitnami/pgbouncer:latest
        env:
          - name: POSTGRESQL_PASSWORD
            value: postgres
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "kill -s SIGUSR1 1 ; sleep 15"]
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432
